app = 'bookworm-coreyja'
primary_region = 'ewr'
kill_signal = 'SIGTERM'
kill_timeout = 60

[build]

[env]
  EYES_TRANSPORT = 'batching'

[mounts]
  source = 'bookworm_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
