app = 'bookworm-coreyja'
primary_region = 'ewr'

[build]

[env]
  EYES_TRANSPORT = 'batching'

[mounts]
  source = 'bookworm_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
